### PR TITLE
Add Android support and fix issue with iOS

### PR DESCRIPTION
**Pull request by GameInstitute**
Linked JavaVM, but crashed in cppsdk
Crash
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.xbox.httpclient.NetworkObserver" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/product/lib64, /system/lib64, /system/product/lib64]]

### CODE REVIEW

**Comment by lugehorsam** [comment]
Thanks @GameInstitute. I'll add the new Unreal Android `.so` file here when I've built it and then we can do another test.

**Comment by GameInstitute** [comment]
Replace .so with nakama-cpp unreal (ndk r23c), the app was not crashed when createDefaultClient, but crashed at Authentication.

crashreport
[report.txt](https://github.com/heroiclabs/nakama-unreal/files/9639754/report.txt)

**Comment by lugehorsam** [comment]
Thanks @GameInstitute I'll get back to you on this.

**Comment by lugehorsam** [comment]
Still investigating this @GameInstitute but I have two questions for you:

(1) Why did you zip up the Apple frameworks?
(2) Why did you split out the .aar file into multiple .so files?

**Comment by GameInstitute** [comment]
About iOS

iOS native frameworks added by  PublicFrameworks.Add.

Third-party frameworks added by PublicAdditionalFrameworks.Add

Third-party libraries are called frameworks and are connected in this line.
             * 
             * To get the framework and use it in the UE4 build system. It should have the following folder structure:
             *  MyNameFramework.embeddedframework.zip            <== Pack in *.zip can be used in WinRar
             *       -MyNameFramework.embeddedframework
             *           - MyNameFramework.framework                       <== The source framework that is built using xcode

**Pull request closed without merging**
