### PR TITLE
change library path from ios-universal to ios-arm64

### PR DESCRIPTION
**Pull request by lugehorsam**

### CODE REVIEW

**Comment by redbaron** [comment]
but we do build universal binaries, don't we?

**Comment by redbaron** [comment]
https://github.com/heroiclabs/nakama-cpp-mono/blob/main/ci/combine-artifacts.sh#L16-L34

**Comment by lugehorsam** [comment]
@redbaron just for OSX AFAIK

**Comment by lugehorsam** [comment]
@redbaron could you approve?

**Review by redbaron — APPROVED** [review]

**Pull request merged**
