### PR TITLE
Add Android support

### PR DESCRIPTION
**Pull request by GameInstitute**
In Unreal, the `libHttpClient` was replaced by `UnrealHttpTransport` and `UnrealWsTransport`, and I don't want to add another `libc++_shared.so` to my app(may conflict with Unreal's own).

I had decompressed nakama-release.aar(compiled from nakama-sdk with `UNREAL`).
1. `include` folder was from `[nakama-release]/modules/nakama-sdk/include`.
2. `libs`folder was from `[nakama-release]/modules/nakama-sdk/jni`, and removed `libc++_shared.so`.

### CODE REVIEW

**Comment by lugehorsam** [comment]
@GameInstitute thanks for explaining why you had to remove libc++_shared.so from the .aar and use the individal .so libraries. Makes sense to me 👍

**Review by lugehorsam — CHANGES_REQUESTED** [review]
One last change -- could we rename `NakamaUnrealClientFactory` to `NakamaCoreClientFactory` so that people don't confuse it belonging to our `NakamaUnreal` module?

Then this looks good to go. Great work!

**Comment by GameInstitute** [comment]
@lugehorsam Of course. I submitted it.

**Review by lugehorsam — APPROVED** [review]
👍 thanks

**Pull request merged**
